### ISSUE TITLE
Update field aliases and defaults

### ISSUE THREAD

**Issue by jlherring** [USEPA/Scribe-Data-View-Tool#23]
Hey @tommckennon if you could toss the full list of fields in here, I'll provide appropriate aliases and mark which should be on by default. Thanks!

Aliases can be found after the colon for a given field. In general, replace all underscores with spaces.

Here's the list of Field Names to set default visibility for. Please mark which ones should be visible by default.

- [x] Sample_Number: Sample Number
- [x] Sample_Date: Sample Date
- [x] Sample_Type: Sample Type
- [x] Analysis
- [ ] AnalysisGroup: Analysis Group
- [x] Analyte
- [ ] Analyte_FinalName: Analyte Final Name
- [ ] Analytical_Method: Analytical Method
- [ ] Basis
- [ ] CAS_NO: CAS Number
- [ ] CLP_Sample_No: CLP Sample Number
- [ ] Comments
- [ ] Date_Analyzed: Date Analyzed
- [ ] Date_Collected: Date Collected
- [ ] Date_Edit: Date Edit
- [ ] Date_Extracted: Date Extracted
- [ ] Date_Input: Date Input
- [ ] Date_Received: Date Received
- [ ] Detected
- [ ] Dilution_Factor: Dilution Factor
- [ ] EDD_File_Name: EDD File Name
- [ ] Edited_By: Edited By
- [ ] Extraction_Method: Extraction Method
- [ ] Final_Volume: Final Volume
- [ ] Final_Volume_Unit: Final Volume Unit
- [ ] Lab_Batch_No: Lab Batch Number
- [ ] Lab_Coc_No: Lab Coc Number
- [ ] Lab_Location_ID: Lab Location ID
- [ ] Lab_Name: Lab Name
- [ ] Lab_Result_Qualifier: Lab Result Qualifier
- [ ] Lab_Samp_No: Lab Sample Number
- [ ] LabResultsID: Lab Results ID
- [x] Matrix_ID: Matrix ID
- [x] MDL
- [x] MDL_Units: MDL Units
- [ ] Percent_Lipids: Percent Lipids
- [ ] Percent_Moisture: Percent Moisture
- [ ] Percent_Recovery: Percent Recovery
- [ ] Percent_Solids: Percent Solids
- [ ] QA_Comment: QA Comment
- [ ] QA_Date: QA Date
- [ ] QA_UserName: QA Username
- [ ] QAFlag: QA Flad
- [ ] QC_Type: QC Type
- [ ] Quantitation_Limit: Quantitation Limit
- [ ] Quantitation_Limit_Units: Quantitation Limit Units
- [ ] Reportable_Result: Reportable Result
- [x] Reporting_Limit: Reporting Limit
- [x] Reporting_Limit_Units: Reporting Limit Units
- [x] Result
- [x] Result_Qualifier: Result Qualifier
- [ ] Result_Text: Result Text
- [ ] Result_Type_Code: Result Type Code
- [x] Result_Units: Result Units
- [x] Samp_No: Sample Number
- [ ] Sample_Type_Code: Sample Type Code
- [ ] Site_No: Site Number
- [ ] SubSample_Amount: Sub-Sample Amount
- [ ] SubSample_Amount_Unit: Sub-Sample Amount Unit
- [ ] Test_Type: Test Type
- [ ] Total_Or_Disolved: Total/Disolved (anyway we can combine this w/ one below? guessing it just got misspelled in a project somewhere??)
- [x] Total_Or_Dissolved: Total/Dissolved
- [ ] Validation_Level: Validation Level

**Comment by jlherring** [comment]
hey @tommckennon Keep in mind, we still need to clean up the field aliases both in the table AND where you choose fields. the 2 need to match:
![image](https://user-images.githubusercontent.com/17882165/76356255-05f57e00-62ec-11ea-89ef-e7c61ad5f52c.png)

**Comment by tommckennon** [comment]
This has been resolved for both the display visible fields and filter aliases. Snapshot:
![image](https://user-images.githubusercontent.com/28331071/76466990-db67fb80-63a5-11ea-8393-2f4b4a01c6ba.png)
So going to move to review.

**Comment by tommckennon** [comment]
This has been resolved for both the display visible fields and filter aliases. Snapshot:
![image](https://user-images.githubusercontent.com/28331071/76466990-db67fb80-63a5-11ea-8393-2f4b4a01c6ba.png)
So going to move to review.

**Comment by jlherring** [comment]
@tommckennon still seeing quite a few underscores: 
![image](https://user-images.githubusercontent.com/17882165/76773069-45065200-6778-11ea-8d9f-b996cae4a185.png)

**Comment by tommckennon** [comment]
@jlherring  and @tbock, this is handled. One issue. It turns out that there is one Scribe Project DB schema field that looks to be a mistake on their part that's mentioned in this issue. It is that they have two columns which likely represent the same thing (Total_Or_Dissolved and Total_Or_Disolved) in LabResutls table, or perhaps there is a reason they have both fields in the LabResults table. I feel combining the fields together in the backend's automagic process is a path we shouldn't take since it goes into a data cleansing process in an already complicated and runtime intensive backend process. We shouldn't give the client the impression that cleansing the data on the fly is something that technically advisable for this app. If necessary, the appropriate approach for such issues would be to create a data cleansing task that would resolve such issues prior to the DB being connected to the Scribe Explorer. Since the client created these two fields in the Scribe schema, I think the correct way is to not display the column with a mispelled column name (Total_Or_Disolved) and just display the correctly spelled column, or make a note of it in a help dialog for the Scribe Explorer.
